### ISSUE TITLE
ReferenceError: Request is not defined ao rodar o código pela primeira vez

### ISSUE THREAD

**Issue by Pelezi** [Phillipe17Macedo/Church-App#11]
Rodando o projeto do zero, pela primeira vez, clonei o repositório, executei o comando npm i para baixar as dependências e npm run web para iniciar o projeto em web, mas o retorno do terminal foi o seguinte:

npm run web

> @church/app@2.0.8 web
> expo start --web

Starting project at E:\Documents\Programming\Videira\Church-App-main
Starting Metro Bundler
ReferenceError: Request is not defined
ReferenceError: Request is not defined
    at Object.<anonymous> (E:\Documents\Programming\Videira\Church-App-main\node_modules\@expo\server\src\environment.ts:23:28)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (E:\Documents\Programming\Videira\Church-App-main\node_modules\@expo\server\install.js:1:28)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    
    
Sou da Videira em Caruaru Pernambuco, tô desenvolvendo um sistema de gerenciamento de membros e fiquei curioso, vim pesquisar pra ver se achava mais algum projeto de Videira kkkkk

**Comment by Phillipe17Macedo** [comment]
Olá irmão, Graça e Paz.

Me add no zap 34 99931-7302 Phillipe Macedo
